# Generated by Django 5.1.7 on 2025-03-11 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense_tracker_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_name', models.CharField(blank=True, max_length=255, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
